### ISSUE TITLE
运行项目必须使用JDK17吗

### ISSUE THREAD

**Issue by 21-User** [roukaixin/minio-upload#2]
根据您给出的demo整合到我的项目中运行报错：签名验证未通过
![分片上传](https://github.com/roukaixin/minio-upload/assets/100336018/1e5f62a5-a758-46cf-b071-c0140910d96d)

**Comment by roukaixin** [comment]
项目使用的是 spring boot 3 的版本，所有要求 jdk 17，如果你不想用 17 可以降级 spring boot 的版本。
检查一下minio 的账号密码之类的
